pin_mem: True
model: slimmable_mbnet_v1_bn_uniform
num_choice: 4

sync_bn: false
opt: sgd
sched: cosine
epochs: 30
warmup_lr: 1e-5
weight_decay: 0.01
drop: 0.2
model_ema: true
model_ema_decay: 0.997
lr: 0.08
batch_size: 64
optimizer_step: 1 # step optimizer every * training steps to simulate large batch
drop-path: 0.0
aa: rand-m9-mstd0.5
remode: pixel
reprob: 0.2
smoothing: 0.1
mixup: 0.
color_jitter: 0.06
amp: false
validation_batch_size_multiplier: 4
warmup_epochs: 0
workers: 10
pretrained: false
resume: '' # Your supernet checkpoint after reset bn
no_resume_opt: true
start_epoch: 0

train_mode: gate
test_mode: false

slim_train: true
inplace_bootstrap: true
ensemble_ib: false
gate_train: true
start_chn_idx: 0  # start index of the routing space. Only useful if gate_train is set to true
dist_bn: reduce
reset_bn: false
